### ISSUE TITLE
feat: 동아리 목록, 동아리 신청 목록 화면 수정, 필요없는 주석 삭제

### ISSUE THREAD

**Issue by hjm1593** [crew-z/crewz-admin#69]
담당자: 홍종민
기간:  2023.06.08

## Background
- 동아리 목록 및 동아리 신청목록 화면 미흡한 부분 수정, 필요없는 주석 제거

## Todo
- [x] 동아리 목록 등록일 YYYY-mm-dd 형식으로 수정
- [x] 지원금 내역, 동아리 상세보기, 동아리폐부 버튼 위치 조정
- [x] 동아리 신청 목록 테이블 크기 조정
