### ISSUE TITLE
fix: axios 통신 시 ip 주소 변경

### ISSUE THREAD

**Issue by Yewon-dev** [crew-z/crewz-admin#85]
담당자: 김예원
기간: 6/16

## Background
- 배포함에 따라 각자의 ip 주소로 hosting 하기 위해 수정함

## Todo
- [ ] change axios request ip address
- [ ] change index page's connection ip address
- [ ] remove unnecessary annotation
